import { AppBar, Link, Toolbar, Typography } from "@material-ui/core";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import styled from "styled-components";
import IconButton from "@material-ui/core/IconButton";
import MenuIcon from "@material-ui/icons/Menu";
import { makeStyles } from "@material-ui/core/styles";

const menuItems = [
  "Home",
  "About Us",
  "Our Team",
  "Our Services",
  "Specialities",
  "Gallery",
  "News & Articles",
  "Patient & Visitors",
  "Contact Us",
];
const useStyles = makeStyles((theme) => ({
  root: {
    flexGrow: 1,
  },
  menuButton: {
    marginRight: theme.spacing(2),
  },
  title: {
    flexGrow: 1,
  },
}));

export default function Home() {
  const classes = useStyles();
  return (
    <Container>
      <AppBar position="sticky">
        <Toolbar>
          <IconButton
            className={classes.menuButton}
            edge="start"
            color="inherit"
            aria-label="menu"
          >
            <MenuIcon />
          </IconButton>
          <div style={{ display: "inline-flex", float: "right" }}>
            {menuItems.map((menuItem) => (
              <Typography variant="body2">{menuItem}</Typography>
            ))}
          </div>
        </Toolbar>
      </AppBar>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <main>
        <BannerContainer>
          <Image
            src="/banner-2.jpg"
            alt="Sanjeevani Hospital Lobby"
            // width={500}
            // height={500}
            layout="fill"
            objectFit="cover"
            quality={100}
          />
        </BannerContainer>
      </main>

      <Footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </Footer>
    </Container>
  );
}

const Container = styled.div`
  min-height: 100vh;
`;

const Footer = styled.footer`
  display: flex;
  justify-content: center;
  align-items: center;
  flex-grow: 1;
  background: ${(props) => props.theme.palette.primary.light};
  width: 100%;
  padding: 1rem;
`;

const BannerContainer = styled.div`
  // position: relative !important;
  width: 90vw;
  margin: 0 auto;
  height: 50vh;
  position: relative;
`;
